# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{lolita-translation}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{ITHouse}, %q{Gatis Tomsons}, %q{Arturs Meisters}]
  s.date = %q{2011-08-29}
  s.description = %q{Translates models in Lolita}
  s.email = %q{support@ithouse.lv}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "app/views/components/lolita/translation/_assets.html.erb",
    "app/views/components/lolita/translation/_language_wrap.html.erb",
    "app/views/components/lolita/translation/_switch.html.erb",
    "config/locales/en.yml",
    "config/locales/lv.yml",
    "lib/generators/lolita_translation/USAGE",
    "lib/generators/lolita_translation/assets_generator.rb",
    "lib/generators/lolita_translation/has_translations_generator.rb",
    "lib/generators/lolita_translation/install_generator.rb",
    "lib/lolita-translation.rb",
    "lib/lolita-translation/has_translations.rb",
    "lib/lolita-translation/rails.rb",
    "lib/lolita-translation/string.rb",
    "lib/tasks/has_translations_tasks.rake",
    "lolita-translation.gemspec",
    "public/javascripts/lolita/translation.js",
    "public/stylesheets/lolita/translation.css",
    "spec/has_translations_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/ithouse/lolita-translations}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.8}
  s.summary = %q{Lolita models translation plugin}
  s.test_files = [
    "spec/has_translations_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 3.0.0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<rails>, [">= 3.0.0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, [">= 3.0.0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

